image:
  repository: ghcr.io/deislabs/ratify
  crdRepository: ghcr.io/deislabs/ratify-crds
  tag: v1.0.0-alpha.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
ratifyTestCert: |
  -----BEGIN CERTIFICATE-----
  MIIDNjCCAh6gAwIBAgIQH775NeR9QruFa7zk7yzgWDANBgkqhkiG9w0BAQsFADAdMRswGQYDVQQD
  ExJ3YWJiaXQtbmV0d29ya3MuaW8wHhcNMjIxMDIwMjEyMzU0WhcNMjMxMDIwMjEzMzU0WjAdMRsw
  GQYDVQQDExJ3YWJiaXQtbmV0d29ya3MuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
  AQDGLZtDqEJGdou/m2sPOQLMAaPSGTCaJ4uWw3J56GlD/L0ahIvzaj0LnL1ovRYerUvBemAJtUqy
  FJHobSEUq+eXfpOMs9hbxY8bJ90YYMNh2CZ6vTIDgSKw7JowFJNN6FnjPEPfwV2xAi/CU9r1ijMU
  5m5MImnzbj4JiikdBjtQRPolQNWLubDqCw5hceC2pgcKlpWM//8SodAqu1lPBtlG5BhzPL8bQMAo
  hW8Qe+Jo2J/AxO7Zp/mJFP4ipMhfAHDcQ1CWC0PRIO0qk9JhtSD+o0gQyTXQwFcWi5PgSnMe3rSE
  kmI8WMe+oz7DYDENGz2Pgy7IqtTAphiDycQW6G3ZAgMBAAGjcjBwMA4GA1UdDwEB/wQEAwIFoDAJ
  BgNVHRMEAjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB8GA1UdIwQYMBaAFGFzdC0AfxDJkxM1ZIVx
  BxTrEGvKMB0GA1UdDgQWBBRhc3QtAH8QyZMTNWSFcQcU6xBryjANBgkqhkiG9w0BAQsFAAOCAQEA
  mmXh2QAH03O5+ADia1AXAb97SIAEVSQj6mgYN9E9Os0/3aXDYVLKVShA1OiBidr6Iya9epFBbpzc
  vJv15bGDg+k5KYAsRYSzfQpILADMYW4T/E3uaFBpbt0GYiwTlpRSKnEvyEwf9cRZOouE9CesIn2L
  L0j/+zhBb8RpB7UbrcEL0PXnn/UbnQKkkekpwEOV/USrpT2T/AwE2GUiAzaLj8ps2qgm/4fPj/uh
  w2W7SbZafkVYxirVIdra1Yq2V6BvnnCkbnBLdjAHbQ48+BgiJJTk3QZFofP88tRjGHPYN3TH2Ycv
  Ibo/J0urezLK/M8/QeMkkhY1WClsAi+xLhVWUw==
  -----END CERTIFICATE-----
cosign:
  enabled: false
  key: ""
resources:
   limits:
     cpu: 1000m
     memory: 512Mi
   requests:
     cpu: 600m
     memory: 512Mi
serviceAccount:
  create: false
  name:

# Can be used to authenticate to:
# ACR -> oras.authProviders.azureWorkloadIdentityEnabled
# Key Vault -> akvCertConfig.enabled
azureWorkloadIdentity:
  clientId:

akvCertConfig:
  enabled: false
  vaultName:
  cert1Name:
  cert2Name:
  tenantId:

oras:
  authProviders:
    azureWorkloadIdentityEnabled: false
    k8secretsEnabled: false
    awsEcrBasicEnabled: false

provider:
  auth: ""                  # tls, mtls
  tls:
    skipVerify: true        # skip TLS verification
    crt: ""                 # crt used by ratify (httpserver)
    key: ""                 # key used by ratify (httpserver)
    cabundle: ""            # base64 encoded CA bundle used for the 'caBundle' property for the ratify provider within gatekeeper

podAnnotations: {}
podLabels: {}
enableRuntimeDefaultSeccompProfile: true

rbac:
  create: true
  
upgradeCRDs:
  enabled: false
  extraRules: []

crds:
  affinity: {}
  tolerations: []
  nodeSelector: {kubernetes.io/os: linux}
  resources: {}
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
