# permissions for end users to view verifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verifier-viewer-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/status
  verbs:
  - get
