# permissions for end users to edit verifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verifier-editor-role
rules:
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.ratify.deislabs.io
  resources:
  - verifiers/status
  verbs:
  - get
