{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    heritage: '{{ .Release.Service }}'
    release: '{{ .Release.Name }}'
  name: ratify-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: ratify-admin 
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: ratify-manager-role
  apiGroup: rbac.authorization.k8s.io
  {{- end }}