{{- if .Values.upgradeCRDs.enabled }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ratify-admin-upgrade-crds
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "create", "update", "patch"]
{{- with .Values.upgradeCRDs.extraRules }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ratify-admin-upgrade-crds
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
subjects:
  - kind: ServiceAccount
    name: ratify-admin-upgrade-crds
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ratify-admin-upgrade-crds
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: ratify-admin-upgrade-crds
  namespace: '{{ .Release.Namespace }}'
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
    helm.sh/hook-weight: "1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ratify-update-crds-hook
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ratify.name" . }}
    chart: {{ template "ratify.name" . }}
    ratify.sh/system: "yes"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: ratify-update-crds-hook
      annotations:
        {{- toYaml .Values.podAnnotations | trim | nindent 8 }}
      labels:
        {{- include "ratify.podLabels" . }}
        app: '{{ template "ratify.name" . }}'
        chart: '{{ template "ratify.name" . }}'
        ratify.sh/system: "yes"
        heritage: '{{ .Release.Service }}'
        release: '{{ .Release.Name }}'
    spec:
      serviceAccountName: ratify-admin-upgrade-crds
      restartPolicy: Never      
      containers:
      - name: crds-upgrade
        {{- if not .Values.image.tag }}
        image: '{{ .Values.image.crdRepository }}'
        {{- else }}
        image: '{{ .Values.image.crdRepository }}:{{ .Values.image.tag }}'
        {{- end }}
        imagePullPolicy: '{{ .Values.image.pullPolicy }}'
        args:
        - apply
        - -f
        - crds/
        resources:
          {{- toYaml .Values.crds.resources | nindent 10 }}
        securityContext:
          {{- if .Values.enableRuntimeDefaultSeccompProfile }}
          seccompProfile:
            type: RuntimeDefault
          {{- end }}
          {{- toYaml .Values.crds.securityContext | nindent 10 }}
      {{- with .Values.crds }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      tolerations:
        {{- toYaml .tolerations | nindent 8 }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8 }}
      {{- end }}
{{- end }}
