apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-notary
spec:
  name: notaryv2
  artifactTypes: application/vnd.cncf.notary.v2.signature
  parameters:
    verificationCerts: 
    - /usr/local/ratify-certs
---
{{- if .Values.cosign.enabled }}
apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Verifier
metadata:
  name: verifier-cosign
spec:
  name: cosign
  artifactTypes: org.sigstore.cosign.v1
  parameters:
    key: /usr/local/ratify-certs/cosign.pub
{{- end }}